// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDaDJeDocwIavOzVdjOllq59GCWdnlhQ',
    appId: '1:843705089057:web:763239dd6ca64cb0827760',
    messagingSenderId: '843705089057',
    projectId: 'questionbank-1c424',
    authDomain: 'questionbank-1c424.firebaseapp.com',
    storageBucket: 'questionbank-1c424.firebasestorage.app',
    measurementId: 'G-NM87KKQBFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQcIrJSXzKeCwGHl20EF6khoSTZDB_nD0',
    appId: '1:843705089057:android:471938a34c4c27e9827760',
    messagingSenderId: '843705089057',
    projectId: 'questionbank-1c424',
    storageBucket: 'questionbank-1c424.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALHOQF9ZN_TV7GyNcxTvA1sM0idou9fbo',
    appId: '1:843705089057:ios:84c5782585a52cb5827760',
    messagingSenderId: '843705089057',
    projectId: 'questionbank-1c424',
    storageBucket: 'questionbank-1c424.firebasestorage.app',
    iosBundleId: 'com.example.questionbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALHOQF9ZN_TV7GyNcxTvA1sM0idou9fbo',
    appId: '1:843705089057:ios:84c5782585a52cb5827760',
    messagingSenderId: '843705089057',
    projectId: 'questionbank-1c424',
    storageBucket: 'questionbank-1c424.firebasestorage.app',
    iosBundleId: 'com.example.questionbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMDaDJeDocwIavOzVdjOllq59GCWdnlhQ',
    appId: '1:843705089057:web:d38cf2c99649cffc827760',
    messagingSenderId: '843705089057',
    projectId: 'questionbank-1c424',
    authDomain: 'questionbank-1c424.firebaseapp.com',
    storageBucket: 'questionbank-1c424.firebasestorage.app',
    measurementId: 'G-XB4KYTNHS4',
  );
}
